name: GitHub Snake Animation

on:
  schedule:
    - cron: '0 0 * * *' # roda todo dia Ã  meia-noite
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake SVG and GIF
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: LuAllencar
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit and Push updates
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake.gif
          git commit -m "Update GitHub Snake GIF [skip ci]" || echo "No changes to commit"
          git push
